using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CodeChallenges.UI.MVC
{
    class FibonacciEvenSum
    {
        static void Main(string[] args)
        {
            /*
             * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first
             * 10 terms will be:
             * 
             * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, .....
             * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
             */


            int num1 = 0;
            int num2 = 1;//this starts the process
            int num3 = 0;
            int sum = 0;

            for (int i = 1; i < 34; i++)
            {
                num3 = num1 + num2;//doing all of the adding 
                num1 = num2;//re-establishing initial values by shifting the value
                num2 = num3;//re-establishing initial values
                if (num3 % 2 == 0)
                {
                    sum += num3;//adding the divisibles of 2 aka even numbers
                }
            }
            Console.WriteLine($"{sum:N0}");
        }
    }
}
